//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AmenityReview
    {
        public int reviewID { get; set; }
        public int reviewAmenity { get; set; }
        public System.DateTime dataReview { get; set; }
        public int amenityID { get; set; }
    
        public virtual RoomAmenity RoomAmenity { get; set; }
    }
}
