
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace hotel.Models
{

using System;
    using System.Collections.Generic;
    
public partial class consulta8
{

    public System.DateTime inicio { get; set; }

    public System.DateTime fin { get; set; }

    public Nullable<double> precio { get; set; }

    public string nombre { get; set; }

}

}
