//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Bonification = new HashSet<Bonification>();
            this.Reservation = new HashSet<Reservation>();
        }
    
        public int employeeID { get; set; }
        public string name { get; set; }
        public string lastName { get; set; }
        public System.DateTime DOB { get; set; }
        public decimal salary { get; set; }
        public string placeOfOrigin { get; set; }
        public Nullable<int> cityID { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public int departamentID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bonification> Bonification { get; set; }
        public virtual City City { get; set; }
        public virtual Departament Departament { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservation> Reservation { get; set; }
    }
}
