
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace hotel.Models
{

using System;
    using System.Collections.Generic;
    
public partial class GuestCompanion
{

    public int companionID { get; set; }

    public string name { get; set; }

    public string lastName { get; set; }

    public System.DateTime DOB { get; set; }

    public string email { get; set; }

    public int reservationID { get; set; }



    public virtual Reservation Reservation { get; set; }

}

}
