//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hotel.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class proyecto_hotelEntities : DbContext
    {
        public proyecto_hotelEntities()
            : base("name=proyecto_hotelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AmenityComplaint> AmenityComplaint { get; set; }
        public virtual DbSet<AmenityReview> AmenityReview { get; set; }
        public virtual DbSet<Bonification> Bonification { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Departament> Departament { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Guest> Guest { get; set; }
        public virtual DbSet<GuestCompanion> GuestCompanion { get; set; }
        public virtual DbSet<Invoice> Invoice { get; set; }
        public virtual DbSet<PlaceOfOrigin> PlaceOfOrigin { get; set; }
        public virtual DbSet<Promo> Promo { get; set; }
        public virtual DbSet<Reservation> Reservation { get; set; }
        public virtual DbSet<ReservationComplaint> ReservationComplaint { get; set; }
        public virtual DbSet<ReservationReview> ReservationReview { get; set; }
        public virtual DbSet<ReservationStatus> ReservationStatus { get; set; }
        public virtual DbSet<ReservedFrom> ReservedFrom { get; set; }
        public virtual DbSet<Room> Room { get; set; }
        public virtual DbSet<RoomAmenity> RoomAmenity { get; set; }
        public virtual DbSet<RoomPackage> RoomPackage { get; set; }
        public virtual DbSet<RoomPromo> RoomPromo { get; set; }
        public virtual DbSet<RoomServicePackage> RoomServicePackage { get; set; }
        public virtual DbSet<RoomStatus> RoomStatus { get; set; }
        public virtual DbSet<RoomType> RoomType { get; set; }
        public virtual DbSet<Service> Service { get; set; }
        public virtual DbSet<ServiceType> ServiceType { get; set; }
        public virtual DbSet<State> State { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypeOfBonification> TypeOfBonification { get; set; }
    }
}
