

//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace hotel.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

using System.Data.Entity.Core.Objects;
using System.Linq;


public partial class proyecto_hotelEntities : DbContext
{
    public proyecto_hotelEntities()
        : base("name=proyecto_hotelEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<AmenityComplaint> AmenityComplaint { get; set; }

    public virtual DbSet<AmenityReview> AmenityReview { get; set; }

    public virtual DbSet<Bonification> Bonification { get; set; }

    public virtual DbSet<City> City { get; set; }

    public virtual DbSet<Departament> Departament { get; set; }

    public virtual DbSet<Employee> Employee { get; set; }

    public virtual DbSet<Guest> Guest { get; set; }

    public virtual DbSet<GuestCompanion> GuestCompanion { get; set; }

    public virtual DbSet<Invoice> Invoice { get; set; }

    public virtual DbSet<PlaceOfOrigin> PlaceOfOrigin { get; set; }

    public virtual DbSet<Promo> Promo { get; set; }

    public virtual DbSet<Reservation> Reservation { get; set; }

    public virtual DbSet<ReservationComplaint> ReservationComplaint { get; set; }

    public virtual DbSet<ReservationReview> ReservationReview { get; set; }

    public virtual DbSet<ReservationStatus> ReservationStatus { get; set; }

    public virtual DbSet<ReservedFrom> ReservedFrom { get; set; }

    public virtual DbSet<Room> Room { get; set; }

    public virtual DbSet<RoomAmenity> RoomAmenity { get; set; }

    public virtual DbSet<RoomPackage> RoomPackage { get; set; }

    public virtual DbSet<RoomPromo> RoomPromo { get; set; }

    public virtual DbSet<RoomServicePackage> RoomServicePackage { get; set; }

    public virtual DbSet<RoomStatus> RoomStatus { get; set; }

    public virtual DbSet<RoomType> RoomType { get; set; }

    public virtual DbSet<Service> Service { get; set; }

    public virtual DbSet<ServiceType> ServiceType { get; set; }

    public virtual DbSet<State> State { get; set; }

    public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }

    public virtual DbSet<TypeOfBonification> TypeOfBonification { get; set; }

    public virtual DbSet<consulta1> consulta1 { get; set; }

    public virtual DbSet<consulta2> consulta2 { get; set; }

    public virtual DbSet<reporte10> reporte10 { get; set; }

    public virtual DbSet<reporte3> reporte3 { get; set; }

    public virtual DbSet<reporte4> reporte4 { get; set; }

    public virtual DbSet<reporte5> reporte5 { get; set; }

    public virtual DbSet<reporte6> reporte6 { get; set; }

    public virtual DbSet<consulta11> consulta11 { get; set; }

    public virtual DbSet<consulta12> consulta12 { get; set; }

    public virtual DbSet<consulta8> consulta8 { get; set; }

    public virtual DbSet<DetallesFactura> DetallesFactura { get; set; }


    public virtual ObjectResult<tipo_compra_Result1> tipo_compra()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tipo_compra_Result1>("tipo_compra");
    }


    public virtual ObjectResult<busqueda_reporte10_Result> busqueda_reporte10(Nullable<System.DateTime> inicio, Nullable<System.DateTime> final)
    {

        var inicioParameter = inicio.HasValue ?
            new ObjectParameter("inicio", inicio) :
            new ObjectParameter("inicio", typeof(System.DateTime));


        var finalParameter = final.HasValue ?
            new ObjectParameter("final", final) :
            new ObjectParameter("final", typeof(System.DateTime));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<busqueda_reporte10_Result>("busqueda_reporte10", inicioParameter, finalParameter);
    }


    public virtual ObjectResult<busqueda_reporte11_Result> busqueda_reporte11(Nullable<System.DateTime> inicio, Nullable<System.DateTime> fin)
    {

        var inicioParameter = inicio.HasValue ?
            new ObjectParameter("inicio", inicio) :
            new ObjectParameter("inicio", typeof(System.DateTime));


        var finParameter = fin.HasValue ?
            new ObjectParameter("fin", fin) :
            new ObjectParameter("fin", typeof(System.DateTime));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<busqueda_reporte11_Result>("busqueda_reporte11", inicioParameter, finParameter);
    }


    public virtual ObjectResult<busqueda_reporte12_Result> busqueda_reporte12(Nullable<System.DateTime> inicio, Nullable<System.DateTime> fin)
    {

        var inicioParameter = inicio.HasValue ?
            new ObjectParameter("inicio", inicio) :
            new ObjectParameter("inicio", typeof(System.DateTime));


        var finParameter = fin.HasValue ?
            new ObjectParameter("fin", fin) :
            new ObjectParameter("fin", typeof(System.DateTime));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<busqueda_reporte12_Result>("busqueda_reporte12", inicioParameter, finParameter);
    }


    public virtual ObjectResult<busqueda_reporte3_Result> busqueda_reporte3(Nullable<System.DateTime> inicio, Nullable<System.DateTime> final)
    {

        var inicioParameter = inicio.HasValue ?
            new ObjectParameter("inicio", inicio) :
            new ObjectParameter("inicio", typeof(System.DateTime));


        var finalParameter = final.HasValue ?
            new ObjectParameter("final", final) :
            new ObjectParameter("final", typeof(System.DateTime));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<busqueda_reporte3_Result>("busqueda_reporte3", inicioParameter, finalParameter);
    }


    public virtual ObjectResult<busqueda_reporte4_Result> busqueda_reporte4(Nullable<System.DateTime> inicio, Nullable<System.DateTime> fin)
    {

        var inicioParameter = inicio.HasValue ?
            new ObjectParameter("inicio", inicio) :
            new ObjectParameter("inicio", typeof(System.DateTime));


        var finParameter = fin.HasValue ?
            new ObjectParameter("fin", fin) :
            new ObjectParameter("fin", typeof(System.DateTime));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<busqueda_reporte4_Result>("busqueda_reporte4", inicioParameter, finParameter);
    }


    public virtual ObjectResult<busqueda_reporte5_Result> busqueda_reporte5(Nullable<System.DateTime> inicio, Nullable<System.DateTime> final)
    {

        var inicioParameter = inicio.HasValue ?
            new ObjectParameter("inicio", inicio) :
            new ObjectParameter("inicio", typeof(System.DateTime));


        var finalParameter = final.HasValue ?
            new ObjectParameter("final", final) :
            new ObjectParameter("final", typeof(System.DateTime));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<busqueda_reporte5_Result>("busqueda_reporte5", inicioParameter, finalParameter);
    }


    public virtual ObjectResult<busqueda_reporte7_Result> busqueda_reporte7(Nullable<System.DateTime> inicio, Nullable<System.DateTime> final)
    {

        var inicioParameter = inicio.HasValue ?
            new ObjectParameter("inicio", inicio) :
            new ObjectParameter("inicio", typeof(System.DateTime));


        var finalParameter = final.HasValue ?
            new ObjectParameter("final", final) :
            new ObjectParameter("final", typeof(System.DateTime));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<busqueda_reporte7_Result>("busqueda_reporte7", inicioParameter, finalParameter);
    }


    public virtual ObjectResult<busqueda_reporte8_Result> busqueda_reporte8(Nullable<System.DateTime> inicio, Nullable<System.DateTime> fin)
    {

        var inicioParameter = inicio.HasValue ?
            new ObjectParameter("inicio", inicio) :
            new ObjectParameter("inicio", typeof(System.DateTime));


        var finParameter = fin.HasValue ?
            new ObjectParameter("fin", fin) :
            new ObjectParameter("fin", typeof(System.DateTime));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<busqueda_reporte8_Result>("busqueda_reporte8", inicioParameter, finParameter);
    }


    public virtual ObjectResult<busqueda_reporte9_Result> busqueda_reporte9(Nullable<System.DateTime> inicio, Nullable<System.DateTime> fin)
    {

        var inicioParameter = inicio.HasValue ?
            new ObjectParameter("inicio", inicio) :
            new ObjectParameter("inicio", typeof(System.DateTime));


        var finParameter = fin.HasValue ?
            new ObjectParameter("fin", fin) :
            new ObjectParameter("fin", typeof(System.DateTime));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<busqueda_reporte9_Result>("busqueda_reporte9", inicioParameter, finParameter);
    }

}

}

