
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace hotel.Models
{

using System;
    using System.Collections.Generic;
    
public partial class reporte3
{

    public string promoName { get; set; }

    public System.DateTime startDate { get; set; }

    public System.DateTime endDate { get; set; }

    public Nullable<int> conteo { get; set; }

}

}
