
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace hotel.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ReservationComplaint
{

    public int complaintID { get; set; }

    public int reservationID { get; set; }

    public string comment { get; set; }

    public System.DateTime dateComplaint { get; set; }

    public int departamentID { get; set; }



    public virtual Departament Departament { get; set; }

    public virtual Reservation Reservation { get; set; }

}

}
