
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace hotel.Models
{

using System;
    using System.Collections.Generic;
    
public partial class RoomServicePackage
{

    public int roomServicePackageID { get; set; }

    public int roomPackageID { get; set; }

    public int serviceID { get; set; }



    public virtual RoomPackage RoomPackage { get; set; }

    public virtual Service Service { get; set; }

}

}
